export const defaultUsers = [
  {
    name: "John Doe",
    email: "test1@example.com",
    password: "Qwer!234",
  },
  {
    name: "mohamed nassar",
    email: "test2@example.com",
    password: "Qwer!234",
  },
  {
    name: "mona mohamed",
    email: "test3@example.com",
    password: "Qwer!234",
  },
];

export const products = [
  {
    id: 1,
    name: "Product 1",
    price: 100,
    description: "Description for Product 1",
    image: "https://via.placeholder.com/150",
    quantity: 10,
    category: "Category 1",
  },
  {
    id: 2,
    name: "Product 2",
    price: 200,
    description: "Description for Product 2",
    image: "https://via.placeholder.com/150",
    quantity: 20,
    category: "Category 1",
  },
  {
    id: 3,
    name: "Product 3",
    price: 300,
    description: "Description for Product 3",
    image: "https://via.placeholder.com/150",
    quantity: 30,
    category: "Category 2",
  },
  {
    id: 4,
    name: "Product 4",
    price: 400,
    description: "Description for Product 4",
    image: "https://via.placeholder.com/150",
    quantity: 40,
    category: "Category 2",
  },
  {
    id: 5,
    name: "Product 5",
    price: 500,
    description: "Description for Product 5",
    image: "https://via.placeholder.com/150",
    quantity: 50,
    category: "Category 3",
  },
  {
    id: 6,
    name: "Product 6",
    price: 600,
    description: "Description for Product 6",
    image: "https://via.placeholder.com/150",
    quantity: 60,
    category: "Category 3",
  },
  {
    id: 7,
    name: "Product 7",
    price: 700,
    description: "Description for Product 7",
    image: "https://via.placeholder.com/150",
    quantity: 70,
    category: "Category 4",
  },
  {
    id: 8,
    name: "Product 8",
    price: 800,
    description: "Description for Product 8",
    image: "https://via.placeholder.com/150",
    quantity: 80,
    category: "Category 4",
  },
  {
    id: 9,
    name: "Product 9",
    price: 900,
    description: "Description for Product 9",
    image: "https://via.placeholder.com/150",
    quantity: 90,
    category: "Category 2",
  },
  {
    id: 10,
    name: "Product 10",
    price: 1000,
    description: "Description for Product 10",
    image: "https://via.placeholder.com/150",
    quantity: 100,
    category: "Category 5",
  },
];
